change JSON object to JSON string literal for all BridgeStan owned files
roualdes/bridgestan pull request #66
Opened 2023-01-14 21:38 UTC by roualdes

There are some occurrences of JSON object in files not directly owned by BridgeStan, so I left those out.

2023-01-15 23:06 UTC, bob-carpenter requested changes
I'm confused because the other PR said there were 17 instances:

https://github.com/roualdes/bridgestan/pull/65#discussion_r1070426027

but this PR is only addressing a handful.  If this is the full list, I'm happy to merge.

2023-01-16 23:55 UTC, roualdes commented
Right, I should have been more clear in this PR.  Effectively, the number 17 was wrong.  Some of the 17 occurrences found lived within the Stan submodule, hence in files not directly owned by BridgeStan.  I only changed the occurrences of JSON object in files that are directly owned by BridgeStan, a subset of the 17.    Does that make sense?

2023-01-17 17:59 UTC, bob-carpenter commented
Yes, thanks.  We'll have to clean up in the rest of Stan, too.  As a language dev, I'm particularly sensitive to the distinction between language and reference.

2023-01-17 17:59 UTC, bob-carpenter approved these changes

2023-01-17 17:59 UTC, merged